name: Create README
description: Create README
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  make-readme:
    name: "Generate the README"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: go get github.com/samber/lo@v1
      - name: Create new README
        run: go run main.go
      - name: upload new readme
        uses: actions/upload-artifact@v4
        with:
          name: README.md
          path: README.md
