name: Create README
description: Create README
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  make-readme:
    name: "Generate the README"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: go get github.com/samber/lo@v1
      - name: Create new README
        run: go run main.go
      - name: Push new README
        run: |
          git config user.name crosleyzack
          git config user.email crosleyzack@gmail.com
          git add -f README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "[gh-action] Daily Encounter"
          git push origin main
